### ISSUE TITLE
Response / Request is always empty

### ISSUE THREAD

**Issue by RufusJWB** [springcomp/HttpTrackingMiddleware#2]
I like your tool a lot, but I have the problem, that the `buffer_` of the `ContentStream` always seems to be empty. Did you have this problem as well?

**Comment by springcomp** [comment]
Thanks for your feedback and sorry about your issue.

Do you have a problem with the sample application provided with this code?
Can you elaborate a bit more about how you are using this code.

**Comment by jreyn003** [comment]
If you call the PostStreamAsync() from WebApi.CustomController with post data in the body and content-type application/json the buffer_ property in ContentStream is null.  Basically, if you call the post method with data the program does not read it and display on console window.
