### ISSUE TITLE
HttpException when adding http-trakcking-id?

### ISSUE THREAD

**Issue by BBauer42** [springcomp/HttpTrackingMiddleware#3]
I'm receiving this exception: 
_HttpException was unhandled by user code_

Additional information: _Server cannot append header after HTTP headers have been sent._

This happens on this line: 
_resp.Headers.Add("http-tracking-id", new[] {apiPacket.TrackingId.ToString("d"),});_

**Comment by springcomp** [comment]
Thank you for your feedback and sorry about your issue.

Do you have the problem with the sample application included in this code?
Please, can you elaborate a bit more about how you are hosting this code?
