### ISSUE TITLE
Request is empty for ContentType x-www-form-urlencoded

### ISSUE THREAD

**Issue by YohooE** [springcomp/HttpTrackingMiddleware#4]
First of all, nice solution and it works very well.
Except for logging x-www-form-urlencoded content.

After extending method `IsTextContentType()` to return true if content type equals x-www-form-urlencoded it still logs an empty Request.
The headers shows that there is content (ContentLength greater than zero).
After short investigation I noticed that the `Read()` override (in `ContentStream`) is not accessed if the content type is x-www-form-urlencoded. The form values are passed to the controller, no problem there.

A work-around for this is to call `request.ReadFormAsync()` inside the `Invoke()` method (only if content type is x-www-form-urlencoded). In that case the `Read()` override is called and the request will be logged.
But using this work-around it looks to me that the Form data is read (at least) twice.

Is there a better solution for this issue?

**Comment by Misiu** [comment]
@YohooE I had similar problem, but all I did is extend `IsTextContentType, below is my method:

```CS
private static bool IsTextContentType(string contentType)
{
    if (contentType == null)
        return false;

    var isTextContentType =
        contentType.StartsWith("application/json") ||
        contentType.StartsWith("application/xml") ||
        contentType.StartsWith("text/") ||
        contentType.StartsWith("application/x-www-form-urlencoded")
        ;
    return isTextContentType;
}`
```

I've download code from this repo just yesterday, so maybe something changed in source. Try updating `ContentStream` with latest version.

**Comment by YohooE** [comment]
@Misiu I already extended the "IsTextContentType" but that didn't do the trick.
Maybe the .NET version matters? I'm using 4.6.1

**Comment by Misiu** [comment]
@YohooE I'm using 4.6, but they should be compatible.
The easiest thing You could do is to put breakpoint and debug that method. Maybe You must trim contentType or make it all lowercase.

**Comment by springcomp** [comment]
I updated the code to .netcore 3.0.
The suggestion from @Misiu seems appropriate.
I could not reproduce any problem.
Please, fee free to post a new issue if you want.
